matrix:
  DISTRO:
    - alpine
    - debian
  RUNITOR_VERSION:
    - latest
    - v0.10.1
    - v0.9.2
    - v0.9.1
    - v0.9.0
    - v0.8.0
    - v0.7.2
    - v0.7.1
    - v0.7.1
    - v0.6.0
    - v0.5.0
    - v0.4.0

pipeline:
  build:
    image: docker
    when:
      event: [push]
      branch: main
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - DOCKER_REGISTRY
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
      - DOCKER_REPOSITORY
    commands:
      - echo $${DOCKER_PASSWORD} | docker login --username $${DOCKER_USERNAME} --password-stdin $${DOCKER_REGISTRY}
      - docker build --tag $${DOCKER_REGISTRY}/$${DOCKER_REPOSITORY}:$${RUNITOR_VERSION}-$${DISTRO} --build-arg DISTRO=$${DISTRO} --build-arg RUNITOR_VERSION=$${RUNITOR_VERSION} --file Dockerfile .
      - docker push $${DOCKER_REGISTRY}/$${DOCKER_REPOSITORY}:$${RUNITOR_VERSION}-$${DISTRO}
