---
name: CI to Docker Hub
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Get runitor release versions
        id: get-runitor-versions
        run: echo "::set-output name=runitor_versions::$(curl -s https://api.github.com/repos/bdd/runitor/git/matching-refs/tags/v | jq -c '.|map(.ref|gsub("refs\/tags\/"; ""))')"
    outputs:
      runitor_versions: ${{steps.setup-matrix.outputs.runitor_versions}}

  build:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix:
        distro:
          - alpine
          - debian
        runitor_version: ${{ fromJson(needs.setup-matrix.outputs.runitor_versions)}}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        run: |
          export tag=${{ secrets.DOCKER_REPOSITORY }}/runitor:${{ matrix.runitor_version }}-${{ matrix.distro }}
          docker build \
            --tag ${tag} \
            --build-arg DISTRO=${{ matrix.distro }} \
            --build-arg RUNITOR_VERSION=${{ matrix.runitor_version }} \
            --file Dockerfile .
          docker push ${tag}
