---
name: CI to Docker Hub
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  get_runitor_versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
      - id: get_versions
        run: |
          versions=$(curl -sL https://api.github.com/repos/bdd/runitor/git/matching-refs/tags/ | jq -c '.|map(select(.ref|test("v[0-9]+.[0-9]+.[0-9]+$")))|map(.ref|sub("refs\/tags\/";""))')
          echo ${versions}
          echo ::set-output name=versions::${versions}

  build:
    runs-on: ubuntu-latest
    needs: get_runitor_versions
    strategy:
      matrix:
        distro:
          - alpine
          - debian
        runitor_version: ["v0.1.4","v0.1.5","v0.1.6","v0.1.7","v0.2.0","v0.3.0","v0.3.1","v0.4.0","v0.5.0","v0.6.0","v0.7.0","v0.7.1","v0.7.2","v0.8.0","v0.9.0","v0.9.1","v0.9.2","v0.10.0","v0.10.1"]
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        run: |
          export tag=${{ secrets.DOCKER_REPOSITORY }}/runitor:${{ matrix.runitor_version }}-${{ matrix.distro }}
          docker build \
            --tag ${tag} \
            --build-arg DISTRO=${{ matrix.distro }} \
            --build-arg RUNITOR_VERSION=${{ matrix.runitor_version }} \
            --file Dockerfile .
          docker push ${tag}
