---
name: CI to Docker Hub
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  get_runitor_versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
      - id: get_versions
        run: |
          versions=$(curl -sL https://api.github.com/repos/bdd/runitor/git/matching-refs/tags/ | jq -c '.|map(select(.ref|test("v[0-9]+.[0-9]+.[0-9]+$")))|map(.ref|sub("refs\/tags\/";""))' | jq -c '. + ["latest"]')
          echo ${versions}
          echo ::set-output name=versions::${versions}

  build:
    runs-on: ubuntu-latest
    needs: get_runitor_versions
    strategy:
      matrix:
        distro:
          - name: alpine
            version: 3
          - name: alpine
            version: latest
          - name: debian
            version: 11
          - name: debian
            version: latest
          - name: debian
            version: stable
        runitor_version: ${{ fromJSON(needs.get_runitor_versions.outputs.versions) }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        run: |
          export tag=${{ secrets.DOCKER_REPOSITORY }}/runitor:${{ matrix.runitor_version }}-${{ matrix.distro.name }}_${{ matrix.distro.version }}
          docker build \
            --tag ${tag} \
            --build-arg DISTRO_NAME=${{ matrix.distro.name }} \
            --build-arg DISTRO_VERSION=${{ matrix.distro.version }} \
            --build-arg RUNITOR_VERSION=${{ matrix.runitor_version }} \
            --file Dockerfile .
          docker push ${tag}
