---
name: CI to Docker Hub
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Get runitor release versions
        id: get-runitor-versions
        run: echo ::set-output 'name=runitor_versions::["v0.1.4","v0.1.5","v0.1.6","v0.1.7","v0.2.0","v0.3.0","v0.3.1","v0.4.0","v0.5.0","v0.6.0","v0.7.0-beta.1","v0.7.0-beta.2","v0.7.0-beta.3","v0.7.0-beta.4","v0.7.0","v0.7.1-beta.1","v0.7.1","v0.7.2+build-cgo_disabled","v0.7.2","v0.8.0","v0.9.0-beta.1","v0.9.0-beta.2","v0.9.0","v0.9.1","v0.9.2","v0.10.0-beta.1","v0.10.0-beta.2","v0.10.0-beta.3","v0.10.0-beta.4","v0.10.0-beta.5","v0.10.0-beta.6","v0.10.0","v0.10.1"]'
    outputs:
      runitor_versions: ${{steps.setup-matrix.outputs.runitor_versions}}

  build:
    runs-on: ubuntu-latest
    needs: setup-matrix
    strategy:
      matrix:
        distro:
          - alpine
          - debian
        runitor_versions: ${{ fromJSON(needs.setup-matrix.outputs.runitor_versions) }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        run: |
          export tag=${{ secrets.DOCKER_REPOSITORY }}/runitor:${{ matrix.runitor_version }}-${{ matrix.distro }}
          docker build \
            --tag ${tag} \
            --build-arg DISTRO=${{ matrix.distro }} \
            --build-arg RUNITOR_VERSION=${{ matrix.runitor_version }} \
            --file Dockerfile .
          docker push ${tag}
